// Backward-compatible re-exports. The branches read layer now lives in the resource module
// (`@/lib/api/resources/branches`), generated by `createResourceApi`. These aliases keep existing
// importers working; new resources should import their `*Api` object directly. Remove this shim once
// every branches consumer imports from the resource module.
import { branchesApi } from "@/lib/api/resources/branches";

export type { BranchListParams } from "@/lib/api/resources/branches";

/** Isomorphic list query options (`{ data, page, pageSize, total }`). */
export const branchesQueryOptions = branchesApi.listQuery;
/** Isomorphic single-branch query options. */
export const branchQueryOptions = branchesApi.detailQuery;
